#!/bin/sh
set -e

fatal() { echo "fatal: $*" 1>&2; exit 1; }

[ "$MERCURY_SOCKS" ] || fatal "MERCURY_SOCKS not set"

if [ "$(uname -s)" = "Darwin" ]; then
    cmd="/Applications/Chromium Browser.app/Contents/MacOS/Chromium Browser"
    [ -e "$cmd" ] || fatal "$cmd not found"
else
    cmd="$(basename "$0")"
    command -v "$cmd" >/dev/null || fatal "$cmd not found"
fi

exec "$cmd" \
    --proxy-server="socks5://$MERCURY_SOCKS" \
    --user-data-dir="$HOME/.config/chromium-browser-mercury" \
    --incognito \
    "$@"
